#!/usr/bin/env python3
"""
Test script for Dify file upload/download flow using ticket-based storage (S3/MinIO).

Usage:
    python3 test_upload_flow.py

Environment:
    DIFY_BASE_URL - Dify base URL (default: http://100.66.1.5)
    DIFY_EMAIL    - Login email (default: chuanzegao@163.com)
    DIFY_PASSWORD - Login password (default: 2wsx@WSX)
    APP_ID        - App ID (default: ad247509-825e-4165-96fa-de41278debd7)
"""

import base64
import json
import os
import sys
import time
import requests

# ---------------------------------------------------------------------------
# Configuration
# ---------------------------------------------------------------------------
BASE_URL = os.environ.get("DIFY_BASE_URL", "http://100.66.1.5").rstrip("/")
EMAIL = os.environ.get("DIFY_EMAIL", "chuanzegao@163.com")
PASSWORD = os.environ.get("DIFY_PASSWORD", "2wsx@WSX")
APP_ID = os.environ.get("APP_ID", "ad247509-825e-4165-96fa-de41278debd7")

# Test file content
TEST_FILENAME = "test_upload_flow.yaml"
TEST_CONTENT = b"""# Test file for upload flow verification
# Generated by test_upload_flow.py

version: '3.8'
services:
  app:
    image: test:latest
    ports:
      - "8080:80"
    environment:
      - TEST_ENV=production
      - DEBUG=false
"""
# Pad to ~80KB to reproduce the original issue
while len(TEST_CONTENT) < 80_000:
    TEST_CONTENT += b"\n# padding line " + str(len(TEST_CONTENT)).encode()
TEST_CONTENT = TEST_CONTENT[:80_000]

# ---------------------------------------------------------------------------
# Step 1: Login
# ---------------------------------------------------------------------------
print("=" * 60)
print("STEP 1: Login")
print("=" * 60)

session = requests.Session()
session.verify = False
session.timeout = 30

resp = session.post(
    f"{BASE_URL}/console/api/login",
    json={"email": EMAIL, "password": base64.b64encode(PASSWORD.encode()).decode()},
    headers={
        "Content-Type": "application/json",
        "Accept": "application/json",
    },
    allow_redirects=False,
)
print(f"  Status: {resp.status_code}")
if resp.status_code not in (200, 201):
    print(f"  Response: {resp.text[:500]}")
    sys.exit(1)

login_data = resp.json()
print(f"  Login OK. Response: {login_data.get('result', 'unknown')}")

# Extract CSRF token from cookies
csrf_token = None
for cookie in session.cookies:
    if cookie.name == "csrf_token":
        csrf_token = cookie.value
        break
print(f"  CSRF token: {csrf_token[:20] if csrf_token else 'NOT FOUND'}...")

if not csrf_token:
    print("  ERROR: No CSRF token found in cookies")
    sys.exit(1)

# Set default headers for all subsequent requests
session.headers.update({
    "X-CSRF-Token": csrf_token,
})

# ---------------------------------------------------------------------------
# Step 2: List asset tree (before)
# ---------------------------------------------------------------------------
print("=" * 60)
print("STEP 2: Get asset tree (before upload)")
print("=" * 60)

resp = session.get(
    f"{BASE_URL}/console/api/apps/{APP_ID}/assets/tree",
    headers={"Accept": "application/json"},
)
print(f"  Status: {resp.status_code}")
tree = resp.json()
children = tree.get("children", [])
print(f"  Current files: {len(children)}")

# ---------------------------------------------------------------------------
# Step 3: Get upload URL
# ---------------------------------------------------------------------------
print("=" * 60)
print("STEP 3: Get upload URL")
print("=" * 60)

size = len(TEST_CONTENT)
payload = {
    "name": TEST_FILENAME,
    "size": size,
    "parent_id": None,
}
print(f"  Requesting upload URL for: {TEST_FILENAME} ({size} bytes)")
resp = session.post(
    f"{BASE_URL}/console/api/apps/{APP_ID}/assets/files/upload",
    json=payload,
    headers={
        "Content-Type": "application/json",
        "Accept": "application/json",
    },
)
print(f"  Status: {resp.status_code}")
if resp.status_code not in (200, 201):
    print(f"  Error: {resp.text[:500]}")
    sys.exit(1)

data = resp.json()
node = data["node"]
upload_url = data["upload_url"]
node_id = node["id"]
print(f"  Node ID: {node_id}")
print(f"  Upload URL: {upload_url}")

# Extract token from upload URL for optional PUT test
token = upload_url.rsplit("/", 1)[-1]
print(f"  Token: {token}")

# ---------------------------------------------------------------------------
# Step 4: PUT the file content via upload URL
# ---------------------------------------------------------------------------
print("=" * 60)
print("STEP 4: PUT file content via storage-files upload URL")
print("=" * 60)

try:
    put_resp = session.put(
        upload_url,
        data=TEST_CONTENT,
        headers={
            "Content-Type": "application/octet-stream",
        },
        timeout=30,
    )
    print(f"  Status: {put_resp.status_code}")
    if put_resp.status_code == 204:
        print("  UPLOAD SUCCESS (204 No Content)")
    elif put_resp.status_code == 403:
        print(f"  ERROR: 403 Forbidden")
        print(f"  Response: {put_resp.text[:500]}")
        print("  Possible causes: token expired, wrong op type, or auth issue")
    else:
        print(f"  Response: {put_resp.text[:500]}")
except requests.exceptions.Timeout:
    print("  TIMEOUT: The request to storage-files timed out")
    print("  This may indicate a network issue between API and MinIO")
except Exception as e:
    print(f"  ERROR: {type(e).__name__}: {e}")

# ---------------------------------------------------------------------------
# Step 5: Get file content via API
# ---------------------------------------------------------------------------
print("=" * 60)
print("STEP 5: Get file content via console API")
print("=" * 60)

resp = session.get(
    f"{BASE_URL}/console/api/apps/{APP_ID}/assets/files/{node_id}",
    headers={"Accept": "application/json"},
)
print(f"  Status: {resp.status_code}")
if resp.status_code == 200:
    content_data = resp.json()
    content = content_data.get("content", "")
    print(f"  Content length: {len(content)} characters")
    if content:
        print(f"  First 200 chars: {content[:200]}")
    else:
        print("  WARNING: Empty content returned")
else:
    print(f"  Error: {resp.text[:500]}")

# ---------------------------------------------------------------------------
# Step 6: Get download URL
# ---------------------------------------------------------------------------
print("=" * 60)
print("STEP 6: Get download URL")
print("=" * 60)

resp = session.get(
    f"{BASE_URL}/console/api/apps/{APP_ID}/assets/files/{node_id}/download-url",
    headers={"Accept": "application/json"},
)
print(f"  Status: {resp.status_code}")
if resp.status_code == 200:
    dl_data = resp.json()
    download_url = dl_data.get("download_url", "")
    print(f"  Download URL: {download_url}")
    # Test the download URL
    dl_token = download_url.rsplit("/", 1)[-1]
    print(f"  Testing download...")
    dl_resp = session.get(download_url, timeout=30, stream=True)
    print(f"  Download Status: {dl_resp.status_code}")
    if dl_resp.status_code == 200:
        dl_body = dl_resp.content
        print(f"  Downloaded: {len(dl_body)} bytes")
        if dl_body == TEST_CONTENT[:len(dl_body)]:
            print("  CONTENT MATCHES!")
        else:
            expected = TEST_CONTENT[:len(dl_body)]
            if dl_body[:200] == expected[:200]:
                print("  Content mismatch (possibly truncated)")
            else:
                print(f"  Content MISMATCH! First bytes differ")
    else:
        print(f"  Download failed: {dl_resp.status_code}")
else:
    print(f"  Error: {resp.text[:500]}")

# ---------------------------------------------------------------------------
# Step 7: Delete the uploaded file
# ---------------------------------------------------------------------------
print("=" * 60)
print("STEP 7: Delete the uploaded file")
print("=" * 60)

resp = session.delete(
    f"{BASE_URL}/console/api/apps/{APP_ID}/assets/nodes/{node_id}",
    headers={"Accept": "application/json"},
)
print(f"  Status: {resp.status_code}")
if resp.status_code == 200:
    print("  DELETE SUCCESS")
else:
    print(f"  Delete failed: {resp.text[:500]}")

# ---------------------------------------------------------------------------
# Step 8: Verify deletion (get asset tree after)
# ---------------------------------------------------------------------------
print("=" * 60)
print("STEP 8: Verify deletion (asset tree after)")
print("=" * 60)

resp = session.get(
    f"{BASE_URL}/console/api/apps/{APP_ID}/assets/tree",
    headers={"Accept": "application/json"},
)
print(f"  Status: {resp.status_code}")
after_tree = resp.json()
after_children = after_tree.get("children", [])
print(f"  Remaining files: {len(after_children)}")

print("\n" + "=" * 60)
print("TEST COMPLETE")
print("=" * 60)
